// ============================================================
// PDF GENERATOR
// ------------------------------------------------------------
// Responsible for generating the Agrishield Contract PDF.
//
// Input:
//    Contract Data
//
// Output:
//    PDF saved inside /temp
//
// ============================================================

import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

export const generateContractPDF = async (contract) => {

    return new Promise((resolve, reject) => {

        // -----------------------------------------------------
        // Create Temp Folder if not exists
        // -----------------------------------------------------

        const tempDir = path.join(process.cwd(), "temp");

        if (!fs.existsSync(tempDir)) {
            fs.mkdirSync(tempDir);
        }

        // -----------------------------------------------------
        // File Name
        // -----------------------------------------------------

        const fileName = `${contract.certificateNumber}.pdf`;

        const filePath = path.join(tempDir, fileName);

        // -----------------------------------------------------
        // Create PDF
        // -----------------------------------------------------

        const doc = new PDFDocument({

            size: "A4",

            margin: 50,

        });

        const stream = fs.createWriteStream(filePath);

        doc.pipe(stream);

        // =====================================================
        // HEADER
        // =====================================================

        doc
            .fontSize(24)
            .font("Helvetica-Bold")
            .text("AGRISHIELD", {
                align: "center",
            });

        doc.moveDown(0.3);

        doc
            .fontSize(16)
            .font("Helvetica")
            .text("Digital Agricultural Contract Certificate", {
                align: "center",
            });

        doc.moveDown();

        doc.moveTo(50, doc.y)
            .lineTo(545, doc.y)
            .stroke();

        doc.moveDown();

        // =====================================================
        // Certificate Details
        // =====================================================

        doc.fontSize(12);

        doc.text(`Certificate No : ${contract.certificateNumber}`);

        doc.text(`Generated On   : ${new Date().toLocaleString()}`);

        doc.moveDown();

        // =====================================================
        // Buyer / Farmer
        // =====================================================

        doc.font("Helvetica-Bold");

        doc.text("Farmer Details");

        doc.font("Helvetica");

        doc.text(`Farmer ID : ${contract.farmerId}`);

        doc.moveDown();

        doc.font("Helvetica-Bold");

        doc.text("Buyer Details");

        doc.font("Helvetica");

        doc.text(`Buyer ID : ${contract.buyerId}`);

        doc.moveDown();

        // =====================================================
        // Product
        // =====================================================

        doc.font("Helvetica-Bold");

        doc.text("Contract Details");

        doc.font("Helvetica");

        doc.text(`Quantity : ${contract.quantity} ${contract.unit}`);

        doc.text(`Price    : ₹${contract.pricePerUnit}`);

        doc.text(`Total    : ₹${contract.totalAmount}`);

        doc.moveDown();

        // =====================================================
        // Declaration
        // =====================================================

        doc.font("Helvetica-Bold");

        doc.text("Declaration");

        doc.font("Helvetica");

        doc.text(
            "This Digital Agricultural Contract Certificate is generated by Agrishield after both the buyer and farmer mutually accepted the negotiated terms through the Agrishield platform. This document serves as digital proof of the agreement established between both parties."
        );

        doc.moveDown();

        // =====================================================
        // Terms
        // =====================================================

        doc.font("Helvetica-Bold");

        doc.text("Terms & Conditions");

        doc.font("Helvetica");

        doc.text("• This certificate is digitally generated.");

        doc.text("• Both parties agree to honour the negotiated terms.");

        doc.text("• Failure to fulfil the agreed contract may lead to penalties under Agrishield policies.");

        doc.text("• Fraudulent activities may result in account suspension or permanent banning.");

        doc.moveDown(2);

        // =====================================================
        // Footer
        // =====================================================

        doc.font("Helvetica-Bold");

        doc.text("Digitally Signed By", {
            align: "center",
        });

        doc.moveDown(0.2);

        doc.fontSize(18);

        doc.text("AGRISHIELD", {
            align: "center",
        });

        doc.moveDown();

        doc.fontSize(10);

        doc.text("System Generated Certificate", {
            align: "center",
        });

        doc.end();

        stream.on("finish", () => {

            console.log("✅ PDF Generated");

            resolve(filePath);

        });

        stream.on("error", reject);

    });

};